"""add anonymous + proof_file

Revision ID: 35647a385320
Revises: 
Create Date: 2025-09-21 13:33:00.862506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35647a385320'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('severity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('anonymous', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('proof_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('proof_file')
        batch_op.drop_column('anonymous')
        batch_op.drop_column('severity')
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
